### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by AndreasHeine** [umati/umatiGateway#179]
Hey @GoetzGoerisch,

i get:
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

```yaml
services:

  umatigateway:
    image: ghcr.io/umati/umatigateway:develop
    container_name: umatigateway
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: unless-stopped

```

Have you run that on a Raspberry Pi at some point?
